# Generated by Django 5.1.7 on 2025-03-11 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomepack',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarix'),
        ),
    ]
