# Generated by Django 5.1.7 on 2025-03-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.IntegerField(max_length=20, verbose_name='Telefon Nömrəsi'),
        ),
    ]
