# Generated by Django 5.1.7 on 2025-03-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.IntegerField(verbose_name='Telefon Nömrəsi'),
        ),
    ]
