# Generated by Django 5.1.7 on 2025-03-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contactmessage_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.PositiveBigIntegerField(verbose_name='Telefon Nömrəsi'),
        ),
    ]
