# Generated by Django 5.1.7 on 2025-03-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='complated',
            field=models.BooleanField(default=False, verbose_name='Təhvil verildi'),
        ),
    ]
