# Generated by Django 5.1.7 on 2025-03-11 19:36

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactmessage_complated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=200, verbose_name='Xidmətin adı')),
                ('name_az', models.CharField(default='none', max_length=200, null=True, verbose_name='Xidmətin adı')),
                ('name_en', models.CharField(default='none', max_length=200, null=True, verbose_name='Xidmətin adı')),
                ('name_ru', models.CharField(default='none', max_length=200, null=True, verbose_name='Xidmətin adı')),
                ('desc', ckeditor.fields.RichTextField(default='none', verbose_name='Məzmun')),
                ('desc_az', ckeditor.fields.RichTextField(default='none', null=True, verbose_name='Məzmun')),
                ('desc_en', ckeditor.fields.RichTextField(default='none', null=True, verbose_name='Məzmun')),
                ('desc_ru', ckeditor.fields.RichTextField(default='none', null=True, verbose_name='Məzmun')),
                ('mini_desc', models.TextField(default='none', verbose_name='Kiçik məzmun')),
                ('mini_desc_az', models.TextField(default='none', null=True, verbose_name='Kiçik məzmun')),
                ('mini_desc_en', models.TextField(default='none', null=True, verbose_name='Kiçik məzmun')),
                ('mini_desc_ru', models.TextField(default='none', null=True, verbose_name='Kiçik məzmun')),
                ('img', models.URLField(default='none', verbose_name='Şəkil')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarix')),
            ],
            options={
                'verbose_name': 'Servis',
                'verbose_name_plural': 'Servislər',
            },
        ),
    ]
