# Generated by Django 5.1.7 on 2025-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_whywe'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(default='none', verbose_name='Slug'),
        ),
    ]
