# Generated by Django 5.1.7 on 2025-03-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_services_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WelcomePack',
        ),
    ]
