# Generated by Django 5.1.7 on 2025-03-15 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'CV', 'verbose_name_plural': 'CV-lər'},
        ),
        migrations.AddField(
            model_name='resume',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarix'),
        ),
    ]
