# Generated by Django 5.1.7 on 2025-03-21 23:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='desc_az',
            field=ckeditor.fields.RichTextField(default='none', null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='about',
            name='desc_en',
            field=ckeditor.fields.RichTextField(default='none', null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='about',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(default='none', null=True, verbose_name='Məzmun'),
        ),
    ]
