# Generated by Django 5.1.7 on 2025-03-24 21:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', ckeditor.fields.RichTextField(default='none', verbose_name='Əlaqə məlumatları')),
            ],
            options={
                'verbose_name': 'Əlaqə məlumatları',
                'verbose_name_plural': 'Əlaqə məlumatları',
            },
        ),
    ]
