# Generated by Django 5.1.7 on 2025-03-24 21:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='txt_az',
            field=ckeditor.fields.RichTextField(default='none', null=True, verbose_name='Əlaqə məlumatları'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='txt_en',
            field=ckeditor.fields.RichTextField(default='none', null=True, verbose_name='Əlaqə məlumatları'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='txt_ru',
            field=ckeditor.fields.RichTextField(default='none', null=True, verbose_name='Əlaqə məlumatları'),
        ),
    ]
